version: "3.9"
services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - 3000:3000

  payment:
    build: ./app/payment
    restart: always
    ports:
      - 8001:8001
    depends_on:
      - redis

  inventory:
    build: ./app/inventory
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - redis

  redis:
    image: "redislabs/redisearch:edge"
    ports:
      - 6379:6379
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
